### ISSUE TITLE
not compatible for windows

### ISSUE THREAD

**Issue by yuvarajanS** [openpreserve/scape-xcorrsound#10]
Hi,
I downloaded the source code, try to build the code in windows, Not able to compile in windows..i think the package is not supported for windows..In read me it mentioned only in linux and OS X.

is scape-xcorrsound supports Windows? Can you please provide the steps to do that??

Thanks,
Yuvarajan

**Comment by dec-k** [comment]
I know this is a very dead topic, but @yuvarajanS , would you mind detailing some of the steps you took to overcome the dependency issues? I'm also having trouble compiling on windows.

**Comment by yuvarajanS** [comment]
Steps followed:
1. First compile the dependency software in windows (Boost, fftw)
2. Using cMake I created a visual studio solution file 
3. Open the project in visual studio and tried to add the dependency paths in the project 
4. Compiled and fixed few compiler variant syntax errors like gcc to windows visual studio compiler
5. after that it works :)

**Comment by BorisMolch** [comment]
@dec-k @yuvarajanS 
Hey guys!
I am trying to build for windows, with Cmake gui but it can't find Boost and fftw, even though I downloaded them. I am not sure how to include them.
Any tips would be appreciated !

**Comment by BorisMolch** [comment]
@yuvarajanS 
What do I do about sys/times.h ?

**Comment by BorisMolch** [comment]
Stuck at stage 4 @yuvarajanS  of your steps
