### ISSUE TITLE
xcorrsound documentation problem for sound-index

### ISSUE THREAD

**Issue by revolunet** [openpreserve/scape-xcorrsound#19]
Hi,

I'd like to try `sound-match` but the documentation says

> sound-index builds an index for sound-match to work within

But sound-index is not present in the repo;

Also, `sound-match -h` just mention wav files so i suppose it is the source wav files ?

I'm a little bit confused, any idea please ?

**Comment by blekinge** [comment]
The documentation is somewhat broken at the moment.
This project consist of three major components
* sound-match, which compares two wav files
* overlap-analysis, which finds the overlap between two wav files
* ismir, which is a sound search engine
Ismir consist of three tools
ismir_build_index, which creates an index file from a wav file
ismir_merge, which can merge two index files (to keep down the number of index files)
ismir_query, which takes a wav file and looks for it in the index files

**Comment by blekinge** [comment]
The up2date documentation should be in the man pages for the tools. But you can also see them here
https://github.com/openpreserve/scape-xcorrsound/tree/master/man/man1
The documentation I think you are referencing is
http://xcorrsound.openpreservation.org/
Which is not up2date

**Comment by revolunet** [comment]
Thanks man, will investigate this
